"""add session_id to completions

Revision ID: 537d9c92a9df
Revises: 2317740d89d6
Create Date: 2026-07-11 10:17:05.199286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537d9c92a9df'
down_revision: Union[str, Sequence[str], None] = '2317740d89d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completions', sa.Column('session_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_completions_session_id'), 'completions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_completions_session_id'), table_name='completions')
    op.drop_column('completions', 'session_id')
    # ### end Alembic commands ###
