"""add agent retry logs

Revision ID: c5c174061d77
Revises: ff58fb5c27fb
Create Date: 2026-07-25 15:17:14.396715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c5c174061d77"
down_revision: Union[str, Sequence[str], None] = "ff58fb5c27fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_retry_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("retry_type", sa.String(length=30), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_retry_logs_conversation_id"),
        "agent_retry_logs",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_retry_logs_id"), "agent_retry_logs", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_retry_logs_id"), table_name="agent_retry_logs")
    op.drop_index(
        op.f("ix_agent_retry_logs_conversation_id"), table_name="agent_retry_logs"
    )
    op.drop_table("agent_retry_logs")
    # ### end Alembic commands ###
