"""add conversation memory tables

Revision ID: ff58fb5c27fb
Revises: c4be747607d4
Create Date: 2026-07-17 16:19:27.571317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ff58fb5c27fb"
down_revision: Union[str, Sequence[str], None] = "c4be747607d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_summaries",
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("conversation_id"),
    )
    op.create_table(
        "converstion_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_converstion_messages_conversation_id"),
        "converstion_messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_converstion_messages_created_at"),
        "converstion_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_converstion_messages_id"), "converstion_messages", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_converstion_messages_id"), table_name="converstion_messages")
    op.drop_index(
        op.f("ix_converstion_messages_created_at"), table_name="converstion_messages"
    )
    op.drop_index(
        op.f("ix_converstion_messages_conversation_id"),
        table_name="converstion_messages",
    )
    op.drop_table("converstion_messages")
    op.drop_table("conversation_summaries")
    # ### end Alembic commands ###
